server:
  port: 8080
  servlet:
    context-path: /dyeing

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hf.caigouyun.dyeing.entity


spring:
  datasource:
    username: sysuser
    password: Lyq1990@
    url: jdbc:sqlserver://10.103.88.88:1433;DatabaseName=HSWarpERP
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    vpoolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j2
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mail:
    # 配置 smtp 服务器地址
    host: smtp.exmail.qq.com
    # 发送者邮箱
    username: yunqing.fang@huafeng-cn.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: xLHB3H8eC3xuvqMA
    # 端口号465或587
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: false


